# Generated by Django 3.2.16 on 2025-12-12 16:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0003_auto_20251212_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='title',
            new_name='name',
        ),
    ]
