# Generated by Django 3.2.16 on 2025-12-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0004_rename_title_location_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(
                blank=True, upload_to='post_images', verbose_name='Фото'
            ),
        ),
    ]
