# Generated by Django 3.2.16 on 2025-12-14 18:34
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0006_auto_20251213_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateField(
                help_text='Если установить дату и время в будущем — можно делать отложенные публикации.',
                verbose_name='Дата и время публикации',
            ),
        ),
    ]
